In [1]:
import numpy as np  
import pandas as pd 

In [2]:

arr = np.arange(1, 21) 
print("Исходный массив:", arr)


matrix = arr.reshape(4, 5)
print("\nМатрица 4x5:\n", matrix)

row_sums = matrix.sum(axis=1)
print("\nСумма каждой строки:", row_sums)

max_val = matrix.max()
min_val = matrix.min()
print(f"\nМаксимум: {max_val}, Минимум: {min_val}")

Исходный массив: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Матрица 4x5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Сумма каждой строки: [15 40 65 90]

Максимум: 20, Минимум: 1


In [3]:

data = {
    'Name': ['Алихан', 'Мария', 'Болат', 'Саша', 'Айгерим'],
    'Age': [20, 21, 19, 22, 20],
    'GPA': [3.5, 2.8, 3.9, 3.0, 3.2]
}


df = pd.DataFrame(data)
print("Таблица студентов:\n", df)


good_students = df[df['GPA'] > 3.0]
print("\nСтуденты с GPA > 3.0:\n", good_students)


mean_gpa = df['GPA'].mean()
print(f"\nСредний GPA: {mean_gpa}")


count = len(df)
print(f"Всего студентов: {count}")

Таблица студентов:
       Name  Age  GPA
0   Алихан   20  3.5
1    Мария   21  2.8
2    Болат   19  3.9
3     Саша   22  3.0
4  Айгерим   20  3.2

Студенты с GPA > 3.0:
       Name  Age  GPA
0   Алихан   20  3.5
2    Болат   19  3.9
4  Айгерим   20  3.2

Средний GPA: 3.28
Всего студентов: 5


In [4]:
random_data = np.random.randint(10, 100, size=(10, 3))

df_project = pd.DataFrame(random_data, columns=['A', 'B', 'C'])
print("Сгенерированные данные:\n", df_project.head())


stats = df_project.agg(['min', 'max', 'mean'])
print("\nСтатистика:\n", stats)


df_project.to_csv('my_project_data.csv', index=False)
print("\nФайл 'my_project_data.csv' успешно сохранен.")

Сгенерированные данные:
     A   B   C
0  21  33  78
1  31  98  67
2  69  18  68
3  57  69  56
4  38  56  74

Статистика:
          A     B     C
min   10.0  18.0  11.0
max   95.0  98.0  98.0
mean  47.6  53.5  64.5

Файл 'my_project_data.csv' успешно сохранен.
